---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
- type: document
  path: src/pages/index.js
  label: Home
  match: "**/*"
- type: heading
  label: Golf
- type: heading
  label: Clubhouse
- type: heading
  label: Membership
- type: heading
  label: Contact
- type: heading
  label: Member Portal
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
